### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by Master-Guy** [Ultraporing/ao-id-extractor#7]
Clean copy of the project, opened and build in VS2019. Getting this error when trying to export the items, it doesn't happen when using "Dump all XML".

ItemExtractor.cs, line 41:
```
string aName = node.Attributes["uniquename"].Value;
```

Error:
```
System.NullReferenceException: 'Object reference not set to an instance of an object.'
System.Xml.XmlAttributeCollection.this[string].get returned null.
```

Details:
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=ao-id-extractor
  StackTrace:
   at ao_id_extractor.Extractors.ItemExtractor.ExtractFromXML(String xmlFile, Boolean withLocal) in E:\Programming\ao-id-extractor-master\Extractors\ItemExtractor.cs:line 41
   at ao_id_extractor.Extractors.BaseExtractor.Extract(Boolean withLocal) in E:\Programming\ao-id-extractor-master\Extractors\BaseExtractor.cs:line 73
   at ao_id_extractor.Program.RunExtractions() in E:\Programming\ao-id-extractor-master\Program.cs:line 200
```

**Comment by Ultraporing** [comment]
They changed the XML format with some update. I don't work on this repo anymore, but broderickhyman did pick it up and continues the development. Take a look at his Fork: https://github.com/broderickhyman/ao-id-extractor
